### ISSUE TITLE
Favoritesbar in overviewtab

### ISSUE THREAD

**Issue by HaggitheSecond** [haefele/CTime2#101]
Ability to mark employees as favorites which are then displayed in the overview tab. This would make it easier to see, if "important" coworkers are currently checked-in. 

![mockup2](https://cloud.githubusercontent.com/assets/7889234/19522536/e6f557c2-9617-11e6-9274-cf3da15fae31.png)

(including rather weird english)

**Comment by HaggitheSecond** [comment]
Also, potential Windows-Notifications for the favorite favorites (aka. a special flag or setting) to notify when they check-in or check-out.

**Comment by haefele** [comment]
Not going to do because the new employee-groups kind of do the same thing.
Just not in the overview.
